# Generated by Django 3.1.4 on 2021-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('About', 'about-our-teamtechkenya-company'), ('Services', 'services'), ('Portofolio', 'portofolio'), ('Team', 'teamtechkenya-partners')], max_length=15)),
                ('img', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='home')),
            ],
            options={
                'verbose_name_plural': 'LandingPage',
            },
        ),
        migrations.CreateModel(
            name='Projects_loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projects-done')),
            ],
            options={
                'verbose_name_plural': 'Projects_loan',
            },
        ),
        migrations.CreateModel(
            name='Projects_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projects-done')),
            ],
            options={
                'verbose_name_plural': 'Projects_web',
            },
        ),
        migrations.CreateModel(
            name='Projects_webstartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projects-done')),
            ],
            options={
                'verbose_name_plural': 'Projects_webstartup',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('About', 'about-our-teamtechkenya-company'), ('Services', 'services'), ('Portofolio', 'portofolio'), ('Team', 'teamtechkenya-partners')], max_length=15)),
                ('partner', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='team-members')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
