# Generated by Django 3.1.3 on 2020-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('About', 'about-our-teamtechkenya-company'), ('Services', 'services'), ('Portofolio', 'portofolio'), ('Team', 'teamtechkenya-partners')], max_length=15)),
                ('img', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='home')),
            ],
            options={
                'verbose_name_plural': 'LandingPage',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('About', 'about-our-teamtechkenya-company'), ('Services', 'services'), ('Portofolio', 'portofolio'), ('Team', 'teamtechkenya-partners')], max_length=15)),
                ('partner', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='team-members')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
