# Generated by Django 3.1.3 on 2020-12-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamtechs', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projects-done')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
