# Generated by Django 3.1.3 on 2020-12-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamtechs', '0003_contact_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projects-done')),
            ],
            options={
                'verbose_name_plural': 'Projects_web',
            },
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Projects_loan',
        ),
        migrations.AlterModelOptions(
            name='projects_loan',
            options={'verbose_name_plural': 'Projects_loan'},
        ),
    ]
